export const ADD_ROUTE_TO_COMPLETED = 'ADD_ROUTE_TO_COMPLETED';
export const REMOVE_ROUTE_FROM_COMPLETED = 'REMOVE_ROUTE_FROM_COMPLETED';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const ADD_COMPLETED_ROUTE_INFO = 'ADD_COMPLETED_ROUTE_INFO';
